"""Build explicit-only client packages. This checks files, not agent judgments."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE_REV = '9f3e06f5b9ea9d53d1e48860e318068b9df8d978'
METHOD_SHA256 = 'a03ad586ed0cbac902cf4f9282cea7996086084f6c1483f53ef63bda8f7f6c05'
VERSION = '0.1.0'
CLIENTS = ('codex', 'claude', 'copilot')
FILES = ('SKILL.md', 'references/method.md', 'references/connectlang.md')


def digest(data):
    return hashlib.sha256(data).hexdigest()


def method_reference(root=ROOT):
    source = (root / 'docs/METHOD.md').read_bytes()
    reviewed = json.loads((root / 'docs/rule-review.json').read_text())['docs/METHOD.md']
    if digest(source) != reviewed['sha256'] or digest(source) != METHOD_SHA256:
        raise ValueError('Method text needs its normal rule review before packaging')
    text = source.decode('utf-8').split('## Current evidence includes')[0]
    rows = re.findall(r'^\| (\w+) \| (MUST|SHOULD) \|', text, re.M)
    if len(rows) != 27 or dict(rows) != reviewed['strengths']:
        raise ValueError('Expected all 27 reviewed method rules')
    def link(match):
        target = match.group(1)
        if re.match(r'^[a-z]+:', target) or target.startswith('#'):
            return match.group(0)
        # Source links are relative to docs/METHOD.md, not the skill directory.
        path, sep, anchor = target.partition('#')
        resolved = (root / 'docs' / path).resolve().relative_to(root.resolve())
        return f'](https://github.com/yzm1/upheld/blob/{SOURCE_REV}/{resolved.as_posix()}{sep}{anchor})'
    text = re.sub(r'\]\(([^)]+)\)', link, text)
    header = ('<!-- Generated by tools/package_upheld_skill.py --refresh-reference. -->\n'
              f'<!-- Source commit: {SOURCE_REV}; SHA-256: {digest(source)} -->\n\n')
    return (header + text.rstrip() + '\n').encode()


def check_bundle(root=ROOT):
    base = root / 'skills/upheld'
    for name in (*FILES, 'agents/openai.yaml'):
        path = base / name
        if path.is_symlink() or not path.is_file() or base.resolve() not in path.resolve().parents:
            raise ValueError(f'Missing or unsafe source: {name}')
    if (base / 'references/method.md').read_bytes() != method_reference(root):
        raise ValueError('Bundled rules drifted; review and refresh the method reference')
    for name in FILES:
        text = (base / name).read_text()
        for target in re.findall(r'\]\(([^)]+)\)', text):
            if re.match(r'^[a-z]+:', target) or target.startswith('#'):
                continue
            path = (base / name).parent / target.split('#')[0]
            if base.resolve() not in path.resolve().parents or not path.is_file():
                raise ValueError(f'Broken or escaping skill link: {name}: {target}')
    return base


def build(client, output, root=ROOT):
    if client not in CLIENTS:
        raise ValueError('Unknown client')
    base = check_bundle(root)
    output = Path(output)
    if output.name != 'upheld':
        raise ValueError('Output folder must be named upheld')
    if output.exists() or output.is_symlink():
        raise ValueError('Output already exists; choose a fresh directory')
    payload = {name: (base / name).read_bytes() for name in FILES}
    if client == 'codex':
        payload['agents/openai.yaml'] = (base / 'agents/openai.yaml').read_bytes()
    # Shared discovery directories can expose a Codex package to Copilot too.
    text = payload['SKILL.md'].decode()
    payload['SKILL.md'] = text.replace('---\n', '---\ndisable-model-invocation: true\n', 1).encode()
    payload['LICENSE'] = (root / 'LICENSE').read_bytes()
    payload['NOTICE'] = (root / 'NOTICE').read_bytes()
    manifest = {'version': VERSION, 'client': client, 'method_source_commit': SOURCE_REV,
                'method_source_sha256': digest((root / 'docs/METHOD.md').read_bytes()),
                'files': {name: digest(data) for name, data in sorted(payload.items())}}
    # No shell, downloads, account discovery, global installation, or overwrite.
    output.mkdir(parents=True, exist_ok=False)
    for name, data in payload.items():
        path = output / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    (output / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
    return manifest


def verify_package(output):
    output = Path(output)
    manifest = json.loads((output / 'manifest.json').read_text())
    entries = manifest['files']
    actual = set()
    for path in output.rglob('*'):
        if path.is_symlink():
            raise ValueError('Package contains a symlink')
        if path.is_file() and path != output / 'manifest.json':
            actual.add(path.relative_to(output).as_posix())
    if actual != set(entries):
        raise ValueError('Package files differ from manifest')
    for name, expected in entries.items():
        path = output / name
        if output.resolve() not in path.resolve().parents or digest(path.read_bytes()) != expected:
            raise ValueError(f'Package digest mismatch: {name}')
    return manifest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('--check', action='store_true')
    group.add_argument('--refresh-reference', action='store_true')
    group.add_argument('--client', choices=CLIENTS)
    group.add_argument('--verify', type=Path)
    parser.add_argument('--output', type=Path)
    args = parser.parse_args()
    if bool(args.client) != bool(args.output):
        parser.error('--client and --output must be used together')
    try:
        if args.refresh_reference:
            (ROOT / 'skills/upheld/references/method.md').write_bytes(method_reference())
        elif args.check:
            check_bundle()
        elif args.verify:
            verify_package(args.verify)
        else:
            build(args.client, args.output)
        print('Skill file check completed; agent behavior remains unverified.')
    except (ValueError, OSError, KeyError) as exc:
        print(str(exc), file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
