"""Build explicit-only client packages. This checks files, not agent judgments."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys
import subprocess
import os

ROOT = Path(__file__).resolve().parents[1]
SOURCE_REV = '386a90748f8c6118bf296f1bc0391a172d217f88'
METHOD_SHA256 = 'e245680b5d72751e105eab729caf1458f8a522ee4e6bfec0d75f438e8a1c38eb'
VERSION = '0.1.2'
CLIENTS = ('codex', 'claude', 'copilot')
FILES = ('SKILL.md', 'references/method.md', 'references/connectlang.md')


def digest(data):
    return hashlib.sha256(data).hexdigest()


def method_reference(root=ROOT):
    source = (root / 'docs/METHOD.md').read_bytes()
    reviewed = json.loads((root / 'docs/rule-review.json').read_text())['docs/METHOD.md']
    if digest(source) != reviewed['sha256'] or digest(source) != METHOD_SHA256:
        raise ValueError('Method text needs its normal rule review before packaging')
    if not re.fullmatch(r'[0-9a-f]{40}', SOURCE_REV):
        raise ValueError('Source revision must be a full commit ID')
    try:
        observed = subprocess.run(
            ['git', '-C', str(root), 'show', f'{SOURCE_REV}:docs/METHOD.md'],
            env={**os.environ, 'GIT_NO_REPLACE_OBJECTS': '1'},
            capture_output=True, timeout=10, check=False)
    except subprocess.TimeoutExpired as exc:
        raise OSError('Could not inspect source commit within 10 seconds') from exc
    if observed.returncode:
        raise OSError('Source commit unavailable; fetch the pinned history before export')
    if digest(observed.stdout) != METHOD_SHA256:
        raise ValueError('Source commit method differs from the pinned method bytes')
    text = source.decode('utf-8').split('## Current evidence includes')[0]
    rows = re.findall(r'^\| (\w+) \| (MUST|SHOULD) \|', text, re.M)
    if len(rows) != 27 or dict(rows) != reviewed['strengths']:
        raise ValueError('Expected all 27 reviewed method rules')
    def link(match):
        target = match.group(1)
        if re.match(r'^[a-z]+:', target) or target.startswith('#'):
            return match.group(0)
        # Source links are relative to docs/METHOD.md, not the skill directory.
        path, sep, anchor = target.partition('#')
        resolved = (root / 'docs' / path).resolve().relative_to(root.resolve())
        return f'](https://github.com/yzm1/upheld/blob/{SOURCE_REV}/{resolved.as_posix()}{sep}{anchor})'
    text = re.sub(r'\]\(([^)]+)\)', link, text)
    header = ('<!-- Generated by tools/package_upheld_skill.py --refresh-reference. -->\n'
              f'<!-- Source commit: {SOURCE_REV}; SHA-256: {digest(source)} -->\n\n')
    return (header + text.rstrip() + '\n').encode()


def check_bundle(root=ROOT):
    base = root / 'skills/upheld'
    for name in (*FILES, 'agents/openai.yaml'):
        path = base / name
        if path.is_symlink() or not path.is_file() or base.resolve() not in path.resolve().parents:
            raise ValueError(f'Missing or unsafe source: {name}')
    if (base / 'references/method.md').read_bytes() != method_reference(root):
        raise ValueError('Bundled rules drifted; review and refresh the method reference')
    for name in FILES:
        text = (base / name).read_text()
        for target in re.findall(r'\]\(([^)]+)\)', text):
            if re.match(r'^[a-z]+:', target) or target.startswith('#'):
                continue
            path = (base / name).parent / target.split('#')[0]
            if base.resolve() not in path.resolve().parents or not path.is_file():
                raise ValueError(f'Broken or escaping skill link: {name}: {target}')
    return base


def build(client, output, root=ROOT):
    if client not in CLIENTS:
        raise ValueError('Unknown client')
    base = check_bundle(root)
    output = Path(output)
    if output.name != 'upheld':
        raise ValueError('Output folder must be named upheld')
    if output.exists() or output.is_symlink():
        raise ValueError('Output already exists; choose a fresh directory')
    payload = {name: (base / name).read_bytes() for name in FILES}
    if client == 'codex':
        payload['agents/openai.yaml'] = (base / 'agents/openai.yaml').read_bytes()
    # Shared discovery directories can expose a Codex package to Copilot too.
    text = payload['SKILL.md'].decode()
    payload['SKILL.md'] = text.replace('---\n', '---\ndisable-model-invocation: true\n', 1).encode()
    payload['LICENSE'] = (root / 'LICENSE').read_bytes()
    payload['NOTICE'] = (root / 'NOTICE').read_bytes()
    manifest = {'version': VERSION, 'client': client, 'method_source_commit': SOURCE_REV,
                'method_source_sha256': digest((root / 'docs/METHOD.md').read_bytes()),
                'files': {name: digest(data) for name, data in sorted(payload.items())}}
    # No shell, downloads, account discovery, global installation, or overwrite.
    output.mkdir(parents=True, exist_ok=False)
    for name, data in payload.items():
        path = output / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    (output / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
    return manifest


def verify_package(output):
    output = Path(output)
    manifest = json.loads((output / 'manifest.json').read_text())
    fields = {'version', 'client', 'method_source_commit', 'method_source_sha256', 'files'}
    if not isinstance(manifest, dict) or set(manifest) != fields:
        raise ValueError('Invalid package manifest fields')
    if manifest['version'] not in ('0.1.0', '0.1.1', VERSION) or manifest['client'] not in CLIENTS:
        raise ValueError('Unsupported package version or client')
    for key, size in [('method_source_commit', 40), ('method_source_sha256', 64)]:
        if not isinstance(manifest[key], str) or not re.fullmatch('[0-9a-f]{' + str(size) + '}', manifest[key]):
            raise ValueError('Invalid package source identity')
    entries = manifest['files']
    required = set(FILES) | {'LICENSE', 'NOTICE'}
    if manifest['client'] == 'codex':
        required.add('agents/openai.yaml')
    if not isinstance(entries, dict) or set(entries) != required:
        raise ValueError('Package manifest must list every required file')
    if any(not isinstance(value, str) or not re.fullmatch('[0-9a-f]{64}', value) for value in entries.values()):
        raise ValueError('Invalid package file digest')
    actual = set()
    for path in output.rglob('*'):
        if path.is_symlink():
            raise ValueError('Package contains a symlink')
        if path.is_file() and path != output / 'manifest.json':
            actual.add(path.relative_to(output).as_posix())
    if actual != set(entries):
        raise ValueError('Package files differ from manifest')
    for name, expected in entries.items():
        path = output / name
        if output.resolve() not in path.resolve().parents or digest(path.read_bytes()) != expected:
            raise ValueError(f'Package digest mismatch: {name}')
    return manifest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('--check', action='store_true')
    group.add_argument('--refresh-reference', action='store_true')
    group.add_argument('--client', choices=CLIENTS)
    group.add_argument('--verify', type=Path)
    parser.add_argument('--output', type=Path)
    args = parser.parse_args()
    if bool(args.client) != bool(args.output):
        parser.error('--client and --output must be used together')
    try:
        if args.refresh_reference:
            (ROOT / 'skills/upheld/references/method.md').write_bytes(method_reference())
        elif args.check:
            check_bundle()
        elif args.verify:
            verify_package(args.verify)
        else:
            build(args.client, args.output)
        print(json.dumps({'result': 'clean', 'limit': 'File checks only; agent behavior remains unverified.'}))
    except OSError as exc:
        print(json.dumps({'result': 'could_not_look', 'error': str(exc)}))
        return 2
    except (ValueError, KeyError, TypeError) as exc:
        print(json.dumps({'result': 'violated', 'error': str(exc)}))
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
